title: ENST 4064: Web Mapping and GIS
description: Portfolio and projects by Henry Roberts-Poyourow
remote_theme: pages-themes/slate

# Enable GitHub Pages plugin
plugins:
  - jekyll-remote-theme
  

# Set navigation order
nav_order: 1

# Add your navigation structure (optional override)
nav:
  - title: "Home"
    url: /
  - title: "About Me"
    url: /about.md
  - title: "Projects"
    url: /projects.md
  - title: "Contact"
    url: /contact.md

# Optional extras
color_scheme: dark
logo: /assets/logo.png
search_enabled: true
